using System;
using System.Collections.Generic;
using System.Text;

namespace STUWard;

internal static class ManagedWardReportBuilder
{
	internal static bool TryBuild(ManagedWardReportSnapshot snapshot, out ManagedWardReportBuildResult result)
	{
		try
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendLine("# Generated by " + snapshot.ModName);
			stringBuilder.AppendLine($"# Generated at UTC: {snapshot.GeneratedAtUtc:O}");
			stringBuilder.AppendLine("# World: " + snapshot.WorldName);
			stringBuilder.AppendLine($"# World UID: {snapshot.WorldUid}");
			stringBuilder.AppendLine("accounts:");
			if (snapshot.Accounts.Count == 0)
			{
				stringBuilder.AppendLine("  {}");
			}
			else
			{
				for (int i = 0; i < snapshot.Accounts.Count; i++)
				{
					ManagedWardReportAccountEntry managedWardReportAccountEntry = snapshot.Accounts[i];
					stringBuilder.AppendLine("  " + FormatYamlScalar(managedWardReportAccountEntry.AccountId) + ":");
					stringBuilder.AppendLine($"    wards: {managedWardReportAccountEntry.WardCount}");
					stringBuilder.AppendLine($"    limit: {managedWardReportAccountEntry.EffectiveLimit}");
					stringBuilder.AppendLine("    override: " + managedWardReportAccountEntry.HasOverride.ToString().ToLowerInvariant());
				}
			}
			AppendWardCountSection(stringBuilder, "unresolved_wards_by_creator_id", snapshot.UnresolvedWardOwnerCounts);
			AppendWardCountSection(stringBuilder, "player_account_map_gaps", snapshot.PlayerAccountMapGapCounts);
			result = new ManagedWardReportBuildResult(stringBuilder.ToString(), snapshot.Accounts.Count, snapshot.TotalTrackedWards, CountWardEntries(snapshot.UnresolvedWardOwnerCounts));
			return true;
		}
		catch
		{
			result = default(ManagedWardReportBuildResult);
			return false;
		}
	}

	private static void AppendWardCountSection(StringBuilder builder, string sectionName, List<KeyValuePair<long, int>> entries)
	{
		builder.AppendLine(sectionName + ":");
		if (entries.Count == 0)
		{
			builder.AppendLine("  {}");
			return;
		}
		for (int i = 0; i < entries.Count; i++)
		{
			KeyValuePair<long, int> keyValuePair = entries[i];
			builder.AppendLine($"  {keyValuePair.Key}: {keyValuePair.Value}");
		}
	}

	private static int CountWardEntries(List<KeyValuePair<long, int>> entries)
	{
		int num = 0;
		for (int i = 0; i < entries.Count; i++)
		{
			num += Math.Max(0, entries[i].Value);
		}
		return num;
	}

	private static string FormatYamlScalar(string value)
	{
		string text = (value ?? string.Empty).Replace("'", "''");
		return "'" + text + "'";
	}
}
